id: P2A436969
initial_creation_type: ocr
source_metadata:
  volumes:
    38bab9ef73fb4214994aadc2c6139ed0:
      base_file: v060.txt
      image_group_id: I1PD95905
      title: ''
      total_pages: 1913
      volume_number: 60
